manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
    - name: ElQDuck
      url-base: https://github.com/ElQDuck
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Bongocat (from https://github.com/dsifry) and my house coat of arms
    - name: nice-view-mod
      remote: ElQDuck
      revision: house-coat-of-arms
  self:
    path: config
